[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "default.vcl.tmpl"

# The location to place the rendered configuration file
dest = "/etc/varnish/default.vcl"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "/airship/nginx" ]

# File ownership and mode information
owner = "root"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
# check_cmd = "varnishd -C -f /etc/varnish/default.vcl"
# check_cmd = "/etc/init.d/varnish configtest"
# !!! This will fail with 0 backends. if it fails, it will not restart
# need to be true to reload config and self heal
check_cmd = "true"
reload_cmd = "source /etc/default/varnish && /etc/init.d/varnish restart"

